[workspace]
authors = ["tokoko <togurgenidze@gmail.com>"]
channels = ["conda-forge"]
name = "adbc-go"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-claude = "npm install -g @anthropic-ai/claude-code"

[dependencies]
libadbc-driver-sqlite = ">=1.7.0,<2"
awscli = ">=2.28.16,<3"
libadbc-driver-flightsql = ">=1.7.0,<2"
libduckdb = ">=1.3.2,<2"
nodejs = ">=24.4.1,<24.5"
# go = ">=1.25.1,<2"
# gopls = ">=0.16.1,<0.17"
gcc = "*"
gxx = "*"

[activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:${LD_LIBRARY_PATH}"
